### PR TITLE
Adds an EllipseTool that functions very similar to the RectangleTool

### PR DESCRIPTION
**Pull request by mejackreed**
This is essentially a port of the RectangleTool but using the Ellipse shape. 

Is there a better way to extend RectangleTool to handle this?

### CODE REVIEW

**Comment by psychobolt** [comment]
Hi. This is a pretty good enhancement. I would love to push a new package build as soon with this feature, even without the code improvement for now. I will probably test this when I get the chance. Can you also include the EllipseTool.md along with the package README.md?

**Comment by mejackreed** [comment]
Thanks for the quick response! I've amended the commit to add it to the README.md.

**Comment by psychobolt** [comment]
Looks good. I will create a new package and release that soon.

**Comment by mejackreed** [comment]
Thanks so much @psychobolt 👏

**Comment by psychobolt** [comment]
New release: [react-paperjs-editor@0.0.11](https://github.com/psychobolt/react-paperjs/releases/tag/%40psychobolt%2Freact-paperjs-editor%400.0.11)

**Pull request merged**
